### ISSUE TITLE
Bump code of conduct to the latest version of the Contributor Covenant

### ISSUE THREAD

**Issue by woodrad** [badpacketsllc/ansible-aws_cli#17]
The project currently is using version 1.4 of the [Contributor Covenant](https://www.contributor-covenant.org). We should bump this to the [latest version](https://www.contributor-covenant.org/version/2/0/code_of_conduct/). This should be reflected in:

- [x] README.md
- [x] CODE_OF_CONDUCT.md
- [x] CONTRIBUTING.md

**Comment by mathewwoodyard-okta** [comment]
Resolved by #23
