### ISSUE TITLE
`gather_facts: no` will prevent this role from running

### ISSUE THREAD

**Issue by tom10271** [badpacketsllc/ansible-aws_cli#20]
Adding this in README.md might be a good idea

**Comment by woodrad** [comment]
I suspect the root cause is the role's defaulting `aws_cli_user` to `ansible_user_id `. Could you try setting `aws_cli_user` in  your playbook's `vars` and see if that fixes things? If you aren't able to get that to work, send along an example playbook and I can see if I can get it to work.

**Comment by woodrad** [comment]
Hey, @tom10271 any luck on getting this to work? I'd like to close this issue if so. If not, let's try to figure it out together.

**Comment by woodrad** [comment]
Issue is stale. Will reopen if requested.
